=== harikrishnad1997/ACCT-6321-DB-MS/Coronel_Morris-DBs/Ch15-DB-Conn-Web-Tech/XML/OrderData.dtd
<!ELEMENT OrderData (ORD_ID,ORD_DATE,CUS_NAME,ORD_SHIPTO,ORD_PRODS*,ORD_TOT)>
<!ELEMENT ORD_ID        (#PCDATA )>
<!ELEMENT ORD_DATE      (#PCDATA )> 		
<!ELEMENT CUS_NAME      (#PCDATA )>
<!ELEMENT ORD_SHIPTO	(#PCDATA )>
<!ELEMENT ORD_PRODS     (P_CODE, P_DESCRIPT, P_QOH, P_PRICE)+>
<!ELEMENT P_CODE	(#PCDATA )>
<!ELEMENT P_DESCRIPT	(#PCDATA )>
<!ELEMENT P_QOH	        (#PCDATA )>
<!ELEMENT P_PRICE	(#PCDATA )>		
<!ELEMENT ORD_TOT   	(#PCDATA )>

=== harikrishnad1997/ACCT-6321-DB-MS/Coronel_Morris-DBs/Ch15-DB-Conn-Web-Tech/XML/OrderData.xml
<?xml version = "1.0"?>
<!DOCTYPE OrderData SYSTEM "OrderData.dtd">
<OrderData>
   <ORD_ID>34583</ORD_ID>
   <ORD_DATE>12/08/2016</ORD_DATE>
   <CUS_NAME>Jill Atkins</CUS_NAME>
   <ORD_SHIPTO>1234 Crown Rd, Chicago, IL34564</ORD_SHIPTO>
   <ORD_PRODS>
      <P_CODE>2309-HB</P_CODE>
      <P_DESCRIPT>Claw Hammer</P_DESCRIPT>	
      <P_QOH>2</P_QOH>	
      <P_PRICE>5.95</P_PRICE>
   </ORD_PRODS>		
   <ORD_PRODS>
      <P_CODE>23114-AA</P_CODE>
      <P_DESCRIPT>Sledge Hammer, 12 lb.</P_DESCRIPT>
      <P_QOH>1</P_QOH>
      <P_PRICE>14.40</P_PRICE>
   </ORD_PRODS>		
   <ORD_TOT>26.30</ORD_TOT>
</OrderData>
