=== harikrishnad1997/ACCT-6321-DB-MS/Coronel_Morris-DBs/Ch15-DB-Conn-Web-Tech/XML/productlist.dtd
<!ELEMENT ProductList (Product+)>
<!ELEMENT Product (P_CODE, P_DESCRIPT, P_INDATE?, P_QOH, P_MIN?,P_PRICE)>
<!ELEMENT P_CODE 	(#PCDATA )>
<!ELEMENT P_DESCRIPT 	(#PCDATA )>
<!ELEMENT P_INDATE 	(#PCDATA )>
<!ELEMENT P_QOH 	(#PCDATA )>
<!ELEMENT P_MIN 	(#PCDATA )>
<!ELEMENT P_PRICE 	(#PCDATA )>

=== harikrishnad1997/ACCT-6321-DB-MS/Coronel_Morris-DBs/Ch15-DB-Conn-Web-Tech/XML/productlistv2.xml
<?xml version ="1.0"?>
<!DOCTYPE ProductList SYSTEM "ProductList.dtd">
<ProductList>
	<Product>
		<P_CODE>23109-HB</P_CODE>
		<P_DESCRIPT>Claw hammer</P_DESCRIPT>
		<P_QOH>23</P_QOH>
		<P_PRICE>5.95</P_PRICE>
	</Product>
	<Product>
		<P_CODE>23114-AA</P_CODE>
		<P_DESCRIPT>Sledge hammer, 12 lb.</P_DESCRIPT>
		<P_QOH>8</P_QOH>
		<P_MIN>5</P_MIN>
		<P_PRICE>14.40</P_PRICE>
	</Product>
</ProductList>
